site_name: OneBot 12 标准草案
repo_name: botuniverse/onebot
repo_url: https://github.com/botuniverse/onebot
edit_uri: blob/master/specs/
docs_dir: specs
theme:
  name: material
  custom_dir: theme
  language: zh
  logo: assets/images/logo-white.png
  favicon: assets/images/logo.png
  palette:
    primary: black
    accent: indigo
  features:
    - navigation.sections
    - navigation.tabs
markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
extra:
  search:
    language: jp # 不支持中文，改成日文好像能搜到一部分中文了（无语）
  analytics:
    provider: google
    property: G-RT0B6ZLNQH
extra_javascript:
  - assets/javascripts/config.js

nav:
  - 主页: index.md
  - 术语表: glossary.md
  - OneBotRPC:
    - 概述: onebotrpc/index.md
    - 通信方式:
      - HTTP: onebotrpc/communication/http.md
      - HTTP Webhook: onebotrpc/communication/http-webhook.md
      - 正向 WebSocket: onebotrpc/communication/websocket.md
      - 反向 WebSocket: onebotrpc/communication/websocket-reverse.md
    - 数据协议:
      - 事件: onebotrpc/data-protocol/event.md
      - 动作请求: onebotrpc/data-protocol/action-request.md
      - 动作响应: onebotrpc/data-protocol/action-response.md
  - 接口定义:
    - 概述: interface/index.md
    - 基本数据类型: interface/basic-types.md
    - 扩展规则: interface/rules.md
    - 元接口:
      - 元事件: interface/meta/events.md
      - 元动作: interface/meta/actions.md
    - 消息接口:
      - 消息数据类型: interface/message/type.md
      - 消息段: interface/message/segments.md
      - 消息动作: interface/message/actions.md
    - 单用户接口（Private / Direct）:
      - 用户消息事件: interface/user/message-events.md
      - 用户通知事件: interface/user/notice-events.md
      - 用户动作: interface/user/actions.md
    - 单级群组接口（Group）:
      - 群消息事件: interface/group/message-events.md
      - 群通知事件: interface/group/notice-events.md
      - 群动作: interface/group/actions.md
    - 两级群组接口（Guild-Channel）:
      - TODO: interface/guild/todo.md
    - 文件接口:
      - 文件动作: interface/file/actions.md
